-- In order to apply the commands below, use console client (psql)

CREATE USER acc WITH PASSWORD 'secret';
CREATE DATABASE acc OWNER acc;
GRANT ALL PRIVILEGES ON DATABASE acc TO acc;

ALTER DATABASE fin SET timezone TO 'Europe/Moscow';

CREATE USER accview WITH PASSWORD 'secret';
CREATE USER accload WITH PASSWORD 'secret';

\c acc acc

GRANT USAGE ON SCHEMA public TO accview;
GRANT USAGE ON SCHEMA public TO accload;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO accview;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO accview;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO accload;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO accload;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO accload;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO accload;

\q
