CREATE USER fin WITH PASSWORD 'secret';
CREATE DATABASE fin OWNER fin;
GRANT ALL PRIVILEGES ON DATABASE fin TO fin;

ALTER DATABASE fin SET timezone TO 'Europe/Moscow';

CREATE USER finview WITH PASSWORD 'secret';
CREATE USER finload WITH PASSWORD 'secret';

\c fin fin

GRANT USAGE ON SCHEMA public TO finview;
GRANT USAGE ON SCHEMA public TO finload;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO finview;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO finview;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO finload;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO finload;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO finload;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO finload;

\q
